### PR TITLE
Create Whyapullreq

### PR DESCRIPTION
**Pull request by misc544**
Not again

### CODE REVIEW

**Comment by cassidyjames** [comment]
Not sure what you're trying to do here.

**Comment by misc544** [comment]
I’m trying to experiment here and submit the commits to a fork, but github keeps making a pull request. Do you know why, @cassidyjames?

**Comment by cassidyjames** [comment]
@misc544 ah, you'll need to fork the project first, and then make your changes directly to that fork (not this upstream project). If you are browsing and trying to edit the files from this project, GitHub assumes you want to submit your changes back to this upstream project.

**Comment by misc544** [comment]
Yeah I though I was in my fork after I had to make a pull request

**Pull request closed without merging**
