### PR TITLE
Unify styling of code blocks inside and outside of figure

### PR DESCRIPTION
**Pull request by michallepicki**
- Set figure margin and max-width only to the direct children of figure (`figure *` -> `figure > *`)
- Keep code styling the same after the above change (`.highlight { pre {  margin: 0; } }`)
- Allow for scrolling through long code horizontally even when it's outside of figure (`.highlight { max-width: 100%; }`)

### CODE REVIEW

**Comment by michallepicki** [comment]
If this breaks anything else that may be inside of figure I'm happy to fix this or take another approach but I think it'd be better if figure didn't apply styles to all children if it doesn't need to :)

**Comment by danrabbit** [comment]
Sorry, can you resolve conflicts on this branch for me? I realized we didn't have a code block in the test post and I accidentally created some conflicts for you doing that :see_no_evil: my bad

**Comment by michallepicki** [comment]
@danrabbit done! I also added a second example so we can test that they now look and work the same.

I assumed we don't want the top and bottom margins on `pre` since that's what I saw on [the elementary blog](https://blog.elementary.io/welcome-to-the-new-blog/#design--styling) but I can bring it back for both examples.

**Comment by michallepicki** [comment]
Hi @danrabbit ! Did you have a chance to check this out?

**Pull request closed without merging**
