### PR TITLE
Fix #2 Code block font size is huge on iOS Safari

### LINKED ISSUE #2: Code block font size is huge on iOS Safari
From https://github.com/elementary/blog/issues/49 by @danrabbit 

>Oops
>
>8299DD54-9B30-4E61-9096-709D22D8AC91

### PR DESCRIPTION
**Pull request by michallepicki**
closes #2

### CODE REVIEW

**Comment by michallepicki** [comment]
this is happening only for code blocks inside `<figure>` because `<figure>` first [sets the font-size to 0](https://github.com/elementary/blog-template/blob/07ae1d7a4224f180a226761669aa8ad32cfd275b/_sass/_figures.scss#L2) to fix some other issues and then code size needs to be [re-set with `rem`](https://github.com/elementary/blog-template/blob/07ae1d7a4224f180a226761669aa8ad32cfd275b/_sass/_figures.scss#L26) instead of [`em` that's applied normally](https://github.com/elementary/blog-template/blob/07ae1d7a4224f180a226761669aa8ad32cfd275b/_sass/_code.scss#L31) because (something times zero is still zero)

If we could get rid of setting font-size to 0 all of this could be simplified but I don't know what's the origin of it

**Comment by cassidyjames** [comment]
@michallepicki sorry if the inline comment there wasn't clear; we set the font-size in `<figure>` because we treat it as a container with inline-block children (i.e. when we have two 50%-wide images). If the font size is >0, then the whitespace between the children elements take up space and cause the images to wrap. We then reset the font size on the child elements we're interested in.

**Comment by michallepicki** [comment]
@cassidyjames can we use flex instead?

**Comment by cassidyjames** [comment]
@michallepicki probably! If you'd like to rework that, you're more than welcome to. :smile:

**Comment by michallepicki** [comment]
I can do that someday but for the time being this is the fix :)

**Comment by cassidyjames** [comment]
@michallepicki sounds good! I'll have @danrabbit take a look since I know he has a dev environment and an iPhone to test with.

**Pull request merged**
